export interface IService {
    name: string;
    desc: string;
    image: string;
    createdAt?: string; // timestamps are optional because they are auto-generated by Mongoose
    updatedAt?: string;
    _id : string,
}
  